# Generated by Django 5.0.4 on 2024-05-14 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(upload_to='media/')),
                ('size', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('download_data', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
