# Generated by Django 5.0.4 on 2024-05-20 14:07

import api_test.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='filemodel',
            old_name='download_data',
            new_name='download_date',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=api_test.models.user_directory_path),
        ),
    ]
