# Generated by Django 5.0.4 on 2024-06-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_rename_created_data_filemodel_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='created_date',
            new_name='upload_date',
        ),
    ]
