# Generated by Django 5.0.4 on 2024-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_rename_created_date_filemodel_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='download_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
